### ISSUE TITLE
Status Offline

### ISSUE THREAD

**Issue by Kenpachi22** [Sintinium/oauth#3]
I'm trying to figure out what's wrong with my minecraft.

I try to play w my friends but Oauth keeps saying Status: Offline
Then, when i try to login and select Microsoft Login - it opens to a website then says "You can now close this browser" 
But still says Status offline.
When I try to join the modpack server my friends created it says "Failed to login: The authentication server is currently down for maintenance" 

Can someone help me please?

**Comment by Sintinium** [comment]
Are you able to login through the normal minecraft launcher and join a server?

**Comment by iharaalvez** [comment]
I am having the same issue. It usually happens when I have my game open for a while though. I need to close my game and restart my launcher for it to connect again.
When clicking to connect to Microsoft account, it shows all messages in MC that it's getting Microsoft and Xbox Live tokens, but it is still offline when the process ends.

**Comment by Sintinium** [comment]
Could you share your log file next time this happens? I can't replicate the issue so my guess is some error is happening and I can't do much without a log

**Comment by Sintinium** [comment]
Also which minecraft version are you using

**Comment by iharaalvez** [comment]
Sure. But again, it happens when I leave Minecraft on menu on idle for a while.
I am using 1.16.5 and I'm using GDLauncher cause I'm using it in a modpack.

**Comment by Sintinium** [comment]
Ok I'll do some testing and see if I can figure it out

**Comment by Sintinium** [comment]
https://www.curseforge.com/minecraft/mc-mods/oauth/files/3507476

I just updated OAuth to show a proper error messages when logging into Microsoft. The only times I can replicate this issue is when my internet is unstable or if Microsoft is having server issues. So I'm closing this issue for now unless someone has an error log on the latest version.
